import React, { createContext, useContext, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { Heart, MapPin, Star, X, Menu, Phone, ChevronRight } from 'lucide-react';
import './styles.css';
import HomePage from './Pages/Home/HomePage';
import VendorDashboard from './Pages/Vendor/VendorDashboard';
import { apiRequest as api } from './lib/api';

const Auth = createContext(); const useAuth = () => useContext(Auth);
const photo = (listing, index = 0) => listing.photos?.[index] || `https://images.unsplash.com/photo-1519167758481-83f550bb49b3?auto=format&fit=crop&w=1000&q=80`;
function Header() { const [open, setOpen] = useState(false); const { user, logout } = useAuth(); const closeMenu = () => setOpen(false); return <header><Link className="brand" to="/" onClick={closeMenu}>Shaadi<span>Scout</span></Link><button className="menu" aria-label="Toggle navigation" aria-expanded={open} onClick={() => setOpen(!open)}><Menu /></button><nav className={open ? 'open' : ''}><a href="/#categories" onClick={closeMenu}>Explore</a><a href="/#our-story" onClick={closeMenu}>About</a><NavLink to="/favourites" onClick={closeMenu}>Favourites</NavLink><NavLink to="/vendor" onClick={closeMenu}>{user?.isVendor ? 'Vendor hub' : 'Become a vendor'}</NavLink>{user ? <button className="link-button" onClick={logout}>Sign out</button> : <Link className="nav-cta" to="/auth" onClick={closeMenu}>Sign in</Link>}</nav></header> }
function Footer(){return <footer><div className="brand">Shaadi<span>Scout</span></div><p>Making wedding planning feel beautifully simple.</p><small>© 2026 ShaadiScout. All rights reserved.</small></footer>}
function ListingCard({ listing }) { const { user } = useAuth(); const [fav, setFav] = useState(false); const toggle = async e => { e.preventDefault(); if (!user) return alert('Please sign in to save favourites.'); const result = await api(`/users/favourites/${listing._id}`, { method: 'POST' }); setFav(result.favourited); }; return <Link to={`/listings/${listing._id}`} className="listing-card"><div className="card-photo"><img src={photo(listing)} alt=""/><button className={fav?'heart active':'heart'} onClick={toggle}><Heart fill={fav?'currentColor':'none'}/></button>{listing.category && <span>{listing.category.name}</span>}</div><div className="card-body"><h3>{listing.name}</h3><p><MapPin size={15}/>{listing.city}{listing.state ? `, ${listing.state}` : ''}</p><div className="card-bottom"><b>From ₹{listing.priceFrom.toLocaleString('en-IN')}</b><em><Star size={15} fill="currentColor"/> {listing.rating?.toFixed(1) || 'New'}</em></div></div></Link> }
function Listings(){const [params,setParams]=useSearchParams(),[data,setData]=useState({items:[]}),[cats,setCats]=useState([]); const [filters,setFilters]=useState({search:params.get('search')||'',city:params.get('city')||'',minRating:params.get('minRating')||'',category:params.get('category')||''}); const load=()=>api('/listings?'+new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v)))).then(setData).catch(()=>{}); useEffect(()=>{api('/categories').then(setCats);load()},[]); const apply=e=>{e.preventDefault();setParams(filters);load()}; return <main className="catalog"><p className="eyebrow">DISCOVER YOUR MATCH</p><h1>Wedding services, curated for you</h1><form className="filters" onSubmit={apply}><input placeholder="Search" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><input placeholder="City" value={filters.city} onChange={e=>setFilters({...filters,city:e.target.value})}/><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{cats.map(c=><option value={c._id} key={c._id}>{c.name}</option>)}</select><select value={filters.minRating} onChange={e=>setFilters({...filters,minRating:e.target.value})}><option value="">Any rating</option><option value="4">4★ & up</option><option value="3">3★ & up</option></select><button>Apply filters</button></form><p className="results">{data.total ?? 0} services found</p><div className="grid">{data.items.map(x=><ListingCard key={x._id} listing={x}/>)}</div>{!data.items.length&&<div className="empty">No listings match those filters yet.</div>}</main>}
function Detail(){const {id}=useParams(),[data,setData]=useState(null),[show,setShow]=useState(false); useEffect(()=>{api(`/listings/${id}`).then(setData).catch(()=>{})},[id]); if(!data)return <main className="loading">Loading listing…</main>; const {listing,reviews}=data; return <main className="detail"><div className="gallery"><img src={photo(listing)} /><img src={photo(listing,1)} /><img src={photo(listing,2)} /></div><div className="detail-layout"><article><p className="eyebrow">{listing.category.name} · {listing.city}</p><h1>{listing.name}</h1><p className="rating"><Star fill="currentColor"/> {listing.rating?.toFixed(1) || 'New'} · {listing.reviewCount || 0} reviews</p><p className="description">{listing.description}</p><h2>What they offer</h2><div className="chips">{listing.amenities?.map(x=><span key={x}>{x}</span>)}</div><h2>Reviews</h2>{reviews.length ? reviews.map(r=><div className="review" key={r._id}><b>{r.user.name}</b><span>{'★'.repeat(r.rating)}</span><p>{r.comment}</p></div>) : <p className="muted">Be the first to share your experience.</p>}</article><aside><p>Starting from</p><strong>₹{listing.priceFrom.toLocaleString('en-IN')}</strong><small>{listing.capacity ? `Up to ${listing.capacity} guests` : 'Custom packages available'}</small><button onClick={()=>setShow(true)}>Request a callback</button><a href={`tel:${listing.contact?.phone || ''}`}><Phone size={17}/> Call {listing.contact?.name || 'vendor'}</a></aside></div>{show&&<InterestModal listing={listing} close={()=>setShow(false)}/>}</main>}
function InterestModal({listing,close}){const [form,setForm]=useState({name:'',phone:'',message:''}),[done,setDone]=useState(false); const submit=async e=>{e.preventDefault();await api(`/listings/${listing._id}/interests`,{method:'POST',body:JSON.stringify(form)});setDone(true)}; return <div className="modal-backdrop"><div className="modal"><button className="close" onClick={close}><X/></button>{done?<><h2>Request received</h2><p>{listing.name} will contact you shortly.</p></>:<><h2>Plan with {listing.name}</h2><p>Leave your details and the team will call you back.</p><form onSubmit={submit}><input required placeholder="Your name" onChange={e=>setForm({...form,name:e.target.value})}/><input required placeholder="Phone number" onChange={e=>setForm({...form,phone:e.target.value})}/><textarea placeholder="Tell us about your event" onChange={e=>setForm({...form,message:e.target.value})}/><button>Send request</button></form></>}</div></div>}
function AuthPage(){const [register,setRegister]=useState(false),[form,setForm]=useState({name:'',email:'',password:''}),[error,setError]=useState(''); const {login}=useAuth(); const navigate=useNavigate(); const submit=async e=>{e.preventDefault();setError('');try{const d=await api(`/auth/${register?'register':'login'}`,{method:'POST',body:JSON.stringify(form)});login(d);navigate('/')}catch(e){setError(e.message)}}; return <main className="auth-page"><section><p className="eyebrow">WELCOME TO SHAADISCOUT</p><h1>{register?'Start planning your celebration':'Welcome back'}</h1><p>Save your favourite wedding experts and reach them when you’re ready.</p></section><form className="auth-card" onSubmit={submit}>{register&&<input required placeholder="Your name" onChange={e=>setForm({...form,name:e.target.value})}/>}<input required type="email" placeholder="Email address" onChange={e=>setForm({...form,email:e.target.value})}/><input required minLength="8" type="password" placeholder="Password" onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="error">{error}</p>}<button>{register?'Create account':'Sign in'}</button><p>{register?'Already have an account?':'New to ShaadiScout?'} <button type="button" className="text-button" onClick={()=>setRegister(!register)}>{register?'Sign in':'Create one'}</button></p></form></main>}
function Favourites(){const [items,setItems]=useState([]),{user}=useAuth();useEffect(()=>{if(user)api('/users/favourites').then(setItems)},[user]);if(!user)return <main className="empty">Sign in to see the services you’ve saved.</main>;return <main className="catalog"><p className="eyebrow">YOUR SHORTLIST</p><h1>Favourite services</h1><div className="grid">{items.map(x=><ListingCard key={x._id} listing={x}/>)}</div>{!items.length&&<div className="empty">Your shortlist is waiting. Explore services and tap the heart to save them.</div>}</main>}
function About(){return <main className="about"><p className="eyebrow">OUR STORY</p><h1>A more joyful way to plan a wedding.</h1><p>ShaadiScout brings trusted local wedding talent together in one thoughtful place. Compare services, explore details, and take your time making choices that feel right.</p><div><section><b>For couples</b><p>Find every essential, from a dream venue to the perfect DJ.</p></section><section><b>For businesses</b><p>Showcase your work to couples who are ready to celebrate.</p></section><section><b>For memories</b><p>More confidence, less juggling, and a day that feels like you.</p></section></div></main>}
function App(){const [user,setUser]=useState(()=>JSON.parse(localStorage.getItem('user')||'null'));const login=d=>{localStorage.setItem('token',d.token);localStorage.setItem('user',JSON.stringify(d.user));setUser(d.user)};const updateUser=changes=>setUser(current=>{const next={...current,...changes};localStorage.setItem('user',JSON.stringify(next));return next});const logout=()=>{localStorage.clear();setUser(null)};return <Auth.Provider value={{user,login,logout,updateUser}}><BrowserRouter><Header/><Routes><Route path="/" element={<HomePage/>}/><Route path="/listings" element={<Listings/>}/><Route path="/listings/:id" element={<Detail/>}/><Route path="/favourites" element={<Favourites/>}/><Route path="/vendor" element={<VendorRoute/>}/><Route path="/auth" element={<AuthPage/>}/><Route path="/about" element={<About/>}/></Routes><Footer/></BrowserRouter></Auth.Provider>};
function VendorRoute(){const {user,updateUser}=useAuth();return <VendorDashboard user={user} updateUser={updateUser}/>};createRoot(document.getElementById('root')).render(<App/>);
